from django.urls import path

from serializers_views.api import views

urlpatterns = [
    path(
        "watchlist-basic-serializer/",
        views.WatchlistBasicSerializerView.as_view(),
        name="watchlist-basic-serializer",
    ),
    path(
        "watchlist-basic-serializer/<int:pk>/",
        views.WatchlistBasicSerializerView.as_view(),
        name="watchlist-detail-basic-serializer",
    ),
    path(
        "watchlist-base-serializer/",
        views.WatchlistBaseSerializerView.as_view(),
        name="watchlist-base-serializer",
    ),
    path(
        "watchlist-model-serializer/",
        views.WatchlistModelSerializerView.as_view(),
        name="watchlist-model-serializer",
    ),
    path(
        "watchlist-model-serializer/<int:pk>/",
        views.WatchlistModelSerializerView.as_view(),
        name="watchlist-detail-model-serializer",
    ),
    path(
        "watchlist-list-serializer/",
        views.WatchlistListSerializerView.as_view(),
        name="watchlist-list-serializer",
    ),
    path(
        "watchlist-hm-serializer/",
        views.WatchlistHMSerializerView.as_view(),
        name="watchlist-hm-serializer",
    ),
    path(
        "watchlist-detail-hm-serializer/<int:pk>/",
        views.WatchlistDetailHMSerializerView.as_view(),
        name="watchlist-detail-hm-serializer",
    ),
    path(
        "watchlist-generic-api/",
        views.WatchlistGAPIView.as_view(),
        name="watchlist-generic-api",
    ),
    path(
        "watchlist-detail-generic-api/<str:title>/",
        views.WatchlistDetailGAPIView.as_view(),
        name="watchlist-detail-generic-api",
    ),
    path(
        "watchlist-list-model-mixin/",
        views.WatchlistListModelMixinView.as_view(),
        name="watchlist-list-model-mixin",
    ),
    path(
        "watchlist-create-model-mixin/",
        views.WatchlistCreateModelMixinView.as_view(),
        name="watchlist-create-model-mixin",
    ),
    path(
        "watchlist-retrieve-model-mixin/<int:pk>/",
        views.WatchlistRetrieveModelMixinView.as_view(),
        name="watchlist-retrieve-model-mixin",
    ),
    path(
        "watchlist-update-model-mixin/<int:pk>/",
        views.WatchlistUpdateModelMixinView.as_view(),
        name="watchlist-update-model-mixin",
    ),
    path(
        "watchlist-destroy-model-mixin/<int:pk>/",
        views.WatchlistDestroyModelMixinView.as_view(),
        name="watchlist-destroy-model-mixin",
    ),
    path(
        "streamplatform-basic-serializer/<int:pk>/",
        views.StreamPlatformBasicSerializerView.as_view(),
        name="streamplatform-basic-serializer",
    ),
    path(
        "streamplatform-detail-hm-serializer/<int:pk>/",
        views.StreamPlatformDetailHMSerializerView.as_view(),
        name="streamplatform-detail-hm-serializer",
    ),
    path(
        "reviewlist-basic-serializer/",
        views.ReviewBasicSerializerView.as_view(),
        name="reviewlist-basic-serializer",
    ),
]
