from django.urls import path

from serializers_views.api import views

urlpatterns = [
    path(
        "watchlist-basic-serializer/",
        views.WatchlistBasicSerializerView.as_view(),
        name="watchlist-basic-serializer",
    ),
    path(
        "watchlist-basic-serializer/<int:pk>/",
        views.WatchlistBasicSerializerView.as_view(),
        name="watchlist-detail-basic-serializer",
    ),
    path(
        "watchlist-model-serializer/",
        views.WatchlistModelSerializerView.as_view(),
        name="watchlist-model-serializer",
    ),
    path(
        "watchlist-model-serializer/<int:pk>/",
        views.WatchlistModelSerializerView.as_view(),
        name="watchlist-detail-model-serializer",
    ),
    path(
        "watchlist-list-serializer/",
        views.WatchlistListSerializerView.as_view(),
        name="watchlist-list-serializer",
    ),
    path(
        "watchlist-hm-serializer/",
        views.WatchlistHMSerializerView.as_view(),
        name="watchlist-hm-serializer",
    ),
    path(
        "watchlist-detail-hm-serializer/<int:pk>/",
        views.WatchlistDetailHMSerializerView.as_view(),
        name="watchlist-detail-hm-serializer",
    ),
    path(
        "streamplatform-basic-serializer/<int:pk>/",
        views.StreamPlatformBasicSerializerView.as_view(),
        name="streamplatform-basic-serializer",
    ),
    path(
        "streamplatform-detail-hm-serializer/<int:pk>/",
        views.StreamPlatformDetailHMSerializerView.as_view(),
        name="streamplatform-detail-hm-serializer",
    ),
    path(
        "reviewlist-basic-serializer/",
        views.ReviewBasicSerializerView.as_view(),
        name="reviewlist-basic-serializer",
    ),
    path(
        "watchlist-base-serializer/",
        views.WatchlistBaseSerializerView.as_view(),
        name="watchlist-base-serializer",
    ),
]
